# Generated by Django 2.0.6 on 2018-07-10 21:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=75)),
                ('coursenumber', models.CharField(max_length=75)),
                ('semesteravailable', models.CharField(max_length=1)),
                ('numbercredits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrereqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MathCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.IntegerField()),
                ('corenumbercredits', models.IntegerField()),
                ('english', models.IntegerField()),
                ('englishnumbercredits', models.IntegerField()),
                ('math', models.IntegerField()),
                ('mathnumbercredits', models.IntegerField()),
                ('speech', models.IntegerField()),
                ('speechnumbercredits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeechCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('degreetrack', models.CharField(choices=[('bachelor of science', 'BACHELOR OF SCIENCE'), ('master of science', 'MASTER OF SCIENCE'), ('doctrate of science', 'DOCTRATE OF SCIENCE')], default='bachelor of science', max_length=50)),
                ('major', models.CharField(choices=[('computer science', 'COMPUTER SCIENCE'), ('more majors coming soon', 'MORE MAJORS COMING SOON')], default='computer science', max_length=50)),
                ('general_classtaken', multiselectfield.db.fields.MultiSelectField(choices=[('gen1000', 'GEN 1000'), ('gen1200', 'GEN 1200')], max_length=100)),
                ('core_classtaken', multiselectfield.db.fields.MultiSelectField(choices=[('csci4350', 'CSCI 4350'), ('csci4500', 'CIST 4500')], max_length=100)),
                ('core_extension_classtaken', multiselectfield.db.fields.MultiSelectField(choices=[('math3100', 'MATH 3100'), ('csci4750', 'CSCI 4750')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('coursenumber', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='corecourse',
            name='coursenumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course'),
        ),
    ]
