# Generated by Django 2.0.6 on 2018-07-11 00:16

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('degreetrack', models.CharField(choices=[('bachelor of science', 'BACHELOR OF SCIENCE'), ('master of science', 'MASTER OF SCIENCE'), ('doctrate of science', 'DOCTRATE OF SCIENCE')], default='bachelor of science', max_length=50)),
                ('major', models.CharField(choices=[('computer science', 'COMPUTER SCIENCE'), ('more majors coming soon', 'MORE MAJORS COMING SOON')], default='computer science', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_classtaken', multiselectfield.db.fields.MultiSelectField(choices=[('gen1000', 'GEN 1000'), ('gen1200', 'GEN 1200')], max_length=100)),
                ('core_classtaken', multiselectfield.db.fields.MultiSelectField(choices=[('csci4350', 'CSCI 4350'), ('csci4500', 'CIST 4500')], max_length=100)),
                ('core_extension_classtaken', multiselectfield.db.fields.MultiSelectField(choices=[('math3100', 'MATH 3100'), ('csci4750', 'CSCI 4750')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.User')),
            ],
        ),
    ]
